### ISSUE TITLE
FT render 的时候只钦定一个 light 太暴力了

### ISSUE THREAD

**Issue by Artoria2e5** [codehz/minecraft-unicode-font-generator#1]
load target (hinting) 里面就有一个 [mono](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_LOAD_TARGET_MONO) 单色有点意思，render 的时候配合 FT_LOAD_MONOCHROME 用

另外，看 https://bugs.mojang.com/browse/MC-41270 提供的样例似乎有彩色这回事，所以[FT_LOAD_COLOR](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_LOAD_COLOR)大概可以看看？

**Comment by codehz** [comment]
mono那个输出格式比较奇葩。。。似乎是单个bit输出（本来是一个多选项）。。。。我研究研究再说

**Comment by codehz** [comment]
彩色弄出来意义不大，不过可以搞。。。minecraft某些地方的文字直接无视半透明和各种色彩。。然后你字体都彩色了，出现不同颜色的字体算会是什么情况呢。。。。测试表明部分支持彩色，但是色彩会叠加，造成的效果就是变黑了(红色字体+绿色输出居然会变深色，看起来叠加规则比较奇怪)。。。我只改了英文，以对比效果
![image](https://cloud.githubusercontent.com/assets/13158903/19138290/474be174-8bad-11e6-9e41-1fca18a9a8e1.png)

**Comment by codehz** [comment]
我大概知道怎么处理了。。。。FT_LOAD_MONOCHROME和 FT_LOAD_TARGET_MONO配合才能自动适配好

**Comment by Artoria2e5** [comment]
> 红色字体+绿色输出居然会变深色，看起来叠加规则比较奇怪

考虑到白色被处理的方式，第一反应是可能用 bitwise and 计算了……我等下开个 GIMP 取一下色。

红色：`ff000d`
深绿：`00aa00`，混合后：`000000`
浅绿：`55ff55`，混合后：`55000d`

真的欸……不知道透明色会怎么样。

**Comment by codehz** [comment]
半透明色在好多地方会被无视。。。也就是直接当作不透明处理

**Comment by Artoria2e5** [comment]
> 半透明色在好多地方会被无视。。。也就是直接当作不透明处理。。。。

这样说的话开 mono 大概是有尺寸优势的……？

**Comment by codehz** [comment]
优势还是有的，FreeType2会对mono渲染做优化，比如可以避免一些笔画粘连问题。。。不过大字号，比如64px(60px)的情况下就没啥意义了，小字号16px(15px)效果明显
3种模式对比：
![image](https://cloud.githubusercontent.com/assets/13158903/19141442/f653df22-8bc7-11e6-8349-f772e48590eb.png)

![image](https://cloud.githubusercontent.com/assets/13158903/19141419/d7248b74-8bc7-11e6-80a7-af6325a672cd.png)

![image](https://cloud.githubusercontent.com/assets/13158903/19141557/11081184-8bc9-11e6-81ed-09bb3a925bc8.png)
这个MONO模式最好用在支持的字体上。。。
文泉驿已炸

尺寸优势——这一点我还没优化。。。理论上可以更小——目前是灰度加透明度双通道模式（准备增加索引模式）
