### ISSUE TITLE
Generate Preview of Specific Page

### ISSUE THREAD

**Issue by JapanYoshi** [codehz/minecraft-unicode-font-generator#2]
I would like the capability to let the generator generate a specific page as a test, so we can tell that it's the right size, setting, etc.

**Comment by codehz** [comment]
I will add this feature later.

**Comment by codehz** [comment]
@JapanYoshi It has been implemented! now you can using
```
./minecraft-unicode-font-generator -v に
```
It will generate
![image](https://user-images.githubusercontent.com/13158903/30768660-70745b44-a03d-11e7-8f4b-08840b89feac.png)
